### ISSUE TITLE
Grid will not work

### ISSUE THREAD

**Issue by goug0035** [goug0035/dsn1675-saas-website#1]
@thomasjbradley

I don't know why my grid will not work. At the medium screen the h1 and nav should be beside each other.

![screen shot 2015-11-16 at 3 29 00 pm](https://cloud.githubusercontent.com/assets/6340296/11193841/dc04a04e-8c76-11e5-89bb-051d007858c9.png)

**Comment by thomasjbradley** [comment]
There's a small typo at the top of the `index.html` file, right here:
https://github.com/goug0035/dsn1675-saas-website/blob/gh-pages/index.html#L10

**Comment by goug0035** [comment]
well dont i feel silly now 

thank you thomas
