### ISSUE TITLE
final comit looks different

### ISSUE THREAD

**Issue by goug0035** [goug0035/dsn1675-saas-website#2]
this is what i have coded and saved on my computer
![screen shot 2015-12-18 at 12 27 13 am](https://cloud.githubusercontent.com/assets/6340296/11890095/b572a000-a51e-11e5-8a9b-ea8f4ca2f078.png)

this it what the online site looks like
![screen shot 2015-12-18 at 12 27 34 am](https://cloud.githubusercontent.com/assets/6340296/11890096/b574c22c-a51e-11e5-9674-cc8b1f223223.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you figure it out; it's looking correct for me now?

**Comment by goug0035** [comment]
ya i was just looking at it too soon after commiting
